### ISSUE TITLE
Issue in Character Batch Job, Error appears in failed jobs list. error below.

### ISSUE THREAD

**Issue by AshN1231** [seatplus/eveapi#650]
https://github.com/seatplus/eveapi/blob/281c315b0ac7309f40987414cf8dc72a32bc4802/src/Jobs/Seatplus/Batch/CharacterBatchJob.php#L205

TypeError: Seatplus\Eveapi\Jobs\Contacts\CorporationContactJob::__construct(): Argument #1 ($corporation_id) must be of type int, null given, called in /var/www/html/vendor/seatplus/eveapi/src/Jobs/Seatplus/Batch/CharacterBatchJob.php on line 205 and defined in /var/www/html/vendor/seatplus/eveapi/src/Jobs/Contacts/CorporationContactJob.php:40

**Comment by herpaderpaldent** [comment]
possible the character affiliation job has not completed yet. It is not possible to not have a corporation.

**Comment by herpaderpaldent** [comment]
Hey @AshN1231 

I just released half of the fix. This will already solve the issue. However chances are, that for those lacking of the character_affiliation the batch job needs to run twice. 

I will create a second fix for this. But it requires a bit more time and i want you to have some fix early on.

**Comment by herpaderpaldent** [comment]
With the release of https://github.com/seatplus/eveapi/releases/tag/3.1.2 i believe this can be closed.
